---
- name: Docker Compose Setup 
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - name: Downloading Docker Compose File
      get_url: 
        url: https://github.com/docker/compose/releases/download/1.25.3/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
    - name: Granting permissions for docker-compose
      file: 
        path: /usr/local/bin/docker-compose
        mode: '0755'
      