---
- name: Docker Setup
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  tasks:
  - name: Updating the repositories cache
    apt:
      update_cache: yes
  - name: Installing Docker Prerequisites
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
  - name: Adding the Docker APT signing key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
      id: 0EBFCD88
  - name: Adding the Docker APT Repository  
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian buster main
      state: present
  - name: Updating the repositories cache
    apt:
      update_cache: yes
  - name: Installing Docker Packages
    apt:
      pkg:
      - docker
      - docker.io
  - name: Adding docker group to apardo user
    user: name=apardo
          groups=docker
          append=yes