---
- name: Virtualbox Setup
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  tasks:
  - name: Adding the VirtualBox APT Repository  
    apt_repository:
      repo: deb https://download.virtualbox.org/virtualbox/debian buster contrib
      state: present
      filename: /etc/apt/source.list.d/virtualbox.list
  - name: Updating the Repositories Cache
    apt:
      update_cache: yes
  - name: Installing the VirtualBox and Vagrant Packages
    apt:
      pkg: 
      - virtualbox
      - vagrant