---
- name: Zoom Setup 
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - name: Installing Zoom Debian Package
      apt:
        deb: https://zoom.us/client/latest/zoom_amd64.deb